//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsCoven.Models.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CovenEntities : DbContext
    {
        public CovenEntities()
            : base("name=CovenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_Usuario> TB_Usuario { get; set; }
        public virtual DbSet<TB_Reunion> TB_Reunion { get; set; }
        public virtual DbSet<TB_ReunionComentario> TB_ReunionComentario { get; set; }
    }
}
