//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsCoven.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Hechizo
    {
        public int id_Hechizo { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public int likes { get; set; }
        public Nullable<int> usuario_id { get; set; }
    
        public virtual TB_Usuario TB_Usuario { get; set; }
    }
}
