//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsCoven.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ReunionComentario
    {
        public int id_ReunionComentario { get; set; }
        public string contenido { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public Nullable<int> reunion_id { get; set; }
    
        public virtual TB_Reunion TB_Reunion { get; set; }
        public virtual TB_Usuario TB_Usuario { get; set; }
    }
}
